---
title: "Boxplot"
output: html_notebook
---

#Boxplot (not normalized)

```{r}
library(SummarizedExperiment)
library(GenomicRanges)
library(dplyr)
library(ggplot2)
library(reshape2)
library(limma)
library(edgeR)

setwd("C:/Users/chabb/Desktop/ETHZ/3. Jahr/6. Semester/Blockkurs/2. Epigenetic mechanism/Project/project6_bc2021")
se <- readRDS("C:/Users/chabb/Desktop/ETHZ/3. Jahr/6. Semester/Blockkurs/2. Epigenetic mechanism/Project/project6_bc2021/data/counts_bins_apa.rds")

counts <- assay(se)
cd <- data.frame(colData(se), stringsAsFactors = F)
log.counts = log2(counts + 1)

boxplot(counts,outline=FALSE, las=2)
boxplot(log.counts,outline=FALSE,las=2)

cpm <- melt(counts)
cpmm <- melt(log2(counts+1))
head(cpm)

#raw plot (not normalized)
ggplot(cpm, aes(x=Var2, y=value))+
  geom_boxplot()theme(axis.text.x = element_text(angle = 90)) + labs(y= "Cpm", x = "Samples")#+
  #coord_cartesian(ylim = quantile(cpm2$value, c(0.01, 0.99)))

#log2 plot (not normalized)
ggplot(cpmm, aes(x=Var2, y=value))+
  geom_boxplot() + theme(axis.text.x = element_text(angle = 90)) + labs(y= "Cpm", x = "Samples")
```


#Boxplot normalized

```{r}
#Normalization
y <- DGEList(counts=counts, samples=cd, group=cd$Samples_ID)
y <- calcNormFactors(y)
norm_counts <- cpm(y, log = TRUE)
cpm2 <- melt(norm_counts)
head(cpm2)

##--------------------------------------------------------------------------------------

ggplot(cpm2, aes(x=Var2, y=value))+
  geom_boxplot()+
  
  coord_cartesian(ylim = quantile(cpm2$value, c(0.01, 0.99)))+ theme(axis.text.x = element_text(angle = 90)) + labs(y= "Cpm", x = "Samples") #+
  #facet_wrap(~Var2, scales = "free_x")
```

#Colored by Group
```{R}
#Merge
cpm3 <- inner_join(cpm2, cd, by=c("Var2" = "Samples_ID"))


ggplot(cpm3, aes(x=Var2, y=value, fill = Group))+
  geom_boxplot()+ 
  scale_fill_manual(values=colgroup)+
  coord_cartesian(ylim = quantile(cpm2$value, c(0.01, 0.99))) +theme(axis.text.x = element_text(angle = 90)) + labs(y= "Cpm", x = "Samples")
```

#Facet
```{R}

ggplot(cpm3, aes(x=Var2, y=value, fill = Group))+
  geom_boxplot()+ scale_fill_manual(values=colgroup) +
  coord_cartesian(ylim = quantile(cpm2$value, c(0.01, 0.99))) +                   
  facet_wrap(~Stage, scales = "free_x") +
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank()) +
  ggtitle("Boxplot very nice") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(y="Cpm", x= element_blank()) 

```

```{R}
library(rcartocolor)

colgroup <- c(cols[1],cols[2])
colgroup <- c(Control = cols[1], MSUS = cols[2])
```

